### PR TITLE
Assign a number to a new RSP only after it’s first approval

### PR DESCRIPTION
**Pull request by ghost**
What do you think?

### CODE REVIEW

**Comment by Nemikolh** [comment]
I'm fine with that change! :+1:

**Comment by ghost** [comment]
The Rust developers use a slightly different solution: instead of just incrementing the RFC number, they assign it the number that Github assigned during the pull request (guaranteed to be unique).
I think their objective was to be able to have a number for every RFC, even the ones that were rejected or are in discussion.

But for a small project like ours, either solution should be fine.

**Comment by ghost** [comment]
We still haven't agreed on that, so what do you prefer? The Rust way? Or the on described in this RSP?

Personally I would prefer the Rust way.

**Comment by Nemikolh** [comment]
I think the Rust way seems easier because we don't have to manually do the incrementation ourselves. So I'm fine with doing it the Rust way instead. (Yeah I'm lazy :stuck_out_tongue_closed_eyes:)

**Comment by ghost** [comment]
Feel free to commit the change (:

**Comment by ghost** [comment]
Now I am OK with it :+1:

**Comment by ghost** [comment]
So be it.

**Pull request merged**
